### ISSUE TITLE
Compatibility with 3.1 "_serialize = true" feature?

### ISSUE THREAD

**Issue by Zuluru** [dereuromark/cakephp-ajax#10]
Looks like `_respondAsAjax` needs a bit of a tweak to properly support the new option of setting `_serialize` to `true` to serialize all view variables? It's currently assuming that `$this->Controller->viewVars['_serialize']` is an array. I'd say that just checking if that is `=== true` and exiting early if so would work. Alternately, only doing the `serializeKeys` portion if it's `!== true`, if you prefer to have only one exit point from functions.

**Comment by dereuromark** [comment]
Are u able to make a PR?

**Comment by Zuluru** [comment]
Done. First time! Hope I did it right...

**Comment by dereuromark** [comment]
Closing as PR is open.
