### ISSUE TITLE
Create PR for CAKE3.0

### ISSUE THREAD

**Issue by Antoniossss** [dereuromark/cakephp-ajax#13]
Hi Mark!

This is not exactly the issue, but can you tell me please why this is not the part of Cake3 core? Cake includes AjaxView for example but it is doing only half of the job

**Comment by dereuromark** [comment]
Because this is an opinionated approach, my personal best practice recommendation.
Anyone else could do it slightly different - thus a plugin is totally OK and sufficient.
Either use it or dont :)
