### ISSUE TITLE
viewClass Deprecated

### ISSUE THREAD

**Issue by jeffreyroberts** [dereuromark/cakephp-ajax#16]
In reference to the docs 

$this->viewClass = 'Ajax.Ajax';

**Comment by dereuromark** [comment]
can u please make a pr? :) that would be awesome!

**Comment by jeffreyroberts** [comment]
word, I think allowOnly is as well, I could use some ajax like that demo, so, I will look into it...

out of the box, I couldnt get it to work with 3.4.x the other day, im going to try again today, i will keep you posted

**Comment by dereuromark** [comment]
check out the sandbox app. it showcases it.

**Comment by dereuromark** [comment]
Resolved with https://github.com/dereuromark/cakephp-ajax/commit/4ab5ed37197a24171c6f0a209beffaad4e5cff27
