### ISSUE TITLE
Deprecation notice

### ISSUE THREAD

**Issue by degee147** [dereuromark/cakephp-ajax#20]
Notice: Deprecated (16384): Response::type() is deprecated. Use getType() or withType() instead. - /vendor/dereuromark/cakephp-ajax/src/View/AjaxView.php, line: 80
 You can disable deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED` in your config/app.php

**Comment by dereuromark** [comment]
This is because of https://github.com/dereuromark/cakephp-ajax/blob/master/composer.json#L17 - as it also supports 3.5 still as outlined in the readme.

Feel free to make a PR to bump the whole thing to 3.6 :)

**Comment by dereuromark** [comment]
3.6 but yeah

**Comment by Zuluru** [comment]
I meant backwardly, not forwardly, but I guess it supports even earlier versions than 3.5.
