### ISSUE TITLE
Doesn't work with new Authorization plugin

### ISSUE THREAD

**Issue by Zuluru** [dereuromark/cakephp-ajax#28]
The new middleware-based plugin architecture does not trigger the beforeRedirect event, thus breaking the Ajax component. I built a workaround (my own "unauthorized" handler registered with the Authorization service) that triggers the event manually for now, but it seems the event needs to be triggered on the component registry's event manager, not the global one. I couldn't find a clean way to access the component registry in the handler, so I added a very ugly hack to make it available via a static property of my AppController class:

    $event = new Event('Controller.beforeRedirect', null, [$url, $response]);
    AppController::$__components->getEventManager()->dispatch($event);
    if ($event->isStopped()) {
        $response = $event->result;
    }

Maybe we need a middleware version of the functionality? Seems like a straight-forward implementation, just adjusting the response some as the stack unwinds.

**Comment by dereuromark** [comment]
I agree. For that approach we should refactor into a middleware then.
Are you able to provide a working prototype as PR?

**Comment by Zuluru** [comment]
I should be able to put that together, yes. You'd like to build this as an additional piece within the existing plugin?

**Comment by dereuromark** [comment]
I will then just document when to use what for the time being. 
Some people are using the new approach, others might not yet?

**Comment by Zuluru** [comment]
I think I should be able to have a preliminary version ready today or tomorrow, so maybe no need to do interim updates on the documentation.

**Comment by Zuluru** [comment]
I have something that's working well in my tests so far, but I'm only half way through converting my policies, so have only tested half of my controllers. Would like to have all my tests passing before submitting, to make sure everything is covered. Or I can submit something now for you to look at, if you prefer.

**Comment by dereuromark** [comment]
both is fine.

**Comment by dereuromark** [comment]
Did you provide an additional PR here?
Any documentation you could share on the middleversion version?

**Comment by Zuluru** [comment]
I didn't add that, yet. Pushing more changes adds to the existing PR. I guess branching probably works around that, but I didn't think it was worth setting that up for this. Documentation update will be included.
