### ISSUE TITLE
Not using the subdirectory for view file

### ISSUE THREAD

**Issue by gauravmak** [dereuromark/cakephp-ajax#3]
Mark,

I am using this plugin in my app and I needed to skip the subdirectory for view file like this *src\Template\ajax\ACTION_NAME.ctp* as I am using a new controller for ajax requests.

So, I changed the code here https://github.com/dereuromark/cakephp-ajax/blob/master/src/View/AjaxView.php#L68-L70 and set it to - 
`$this->subDir = null;`

Now, I am not sure if this make a good feature and if yes, how to make this option configurable so that it can be put in the repository. What are you comments on it?

**Comment by dereuromark** [comment]
As the code shows that would not work. You would need to set it to empty string `''` or false.

**Comment by dereuromark** [comment]
There is even a test for it :) https://github.com/dereuromark/cakephp-ajax/blob/master/tests/TestCase/View/AjaxViewTest.php#L117

**Comment by gauravmak** [comment]
Thank you for the update.

Sorry,if I misunderstand anything but setting it to '' or false did not work for me initially. and after checking the test, I came to know setting it to false would work.
As per this - https://github.com/dereuromark/cakephp-ajax/blob/master/tests/TestCase/View/AjaxViewTest.php#L123

So, finally making the change as I specified above did work for me : 
I commented these 3 lines - https://github.com/dereuromark/cakephp-ajax/blob/master/src/View/AjaxView.php#L68-L70 and added - 
`$this->subDir = null;`

Please correct me if I am wrong anywhere. I accept my knowledge with this is very limited and I am not aware about all the related parts of the framework.

**Comment by dereuromark** [comment]
So in your case you still have the problem?
What is your controller code?

**Comment by gauravmak** [comment]
No, my problem is solved after the above change. My view is in *src\Template\CONTROLLER_NAME\*  directory. and working. There is not much code yet. I am yet to put everything as per my requirement.

```
<?php
namespace App\Controller;

use App\Controller\AppController;

/**
 * Ajax Controller
 */
class AjaxController extends AppController
{
    public function initialize()
    {
        $this->loadComponent('Ajax.Ajax');
        $this->request->allowMethod('ajax');
    }
    
    public function favorites() {
        // all code here
    }
}

```

**Comment by dereuromark** [comment]
The idea is that you have not to change the source code here.
So instead, you should be using

    $this->subDir = false;

in your controller action, which you do not do yet it seems.

**Comment by gauravmak** [comment]
I had tried that before making change in source code but it didn't work.

**Comment by dereuromark** [comment]
Can you try to make it work without changing the source code? if nothing works, then we have to find a solution.

**Comment by gauravmak** [comment]
I did try a couple of things but failed. I am a novice with this so.
But, not to worry, I will try more. Thank you for the challenge.
I will update after trying my best.

**Comment by gauravmak** [comment]
No luck :( no options.
I think source code needs to be changed.

**Comment by dereuromark** [comment]
Please check if 3.1 fixes the issue.

**Comment by dereuromark** [comment]
Should be good now.
