### ISSUE TITLE
Disable component for some actions

### ISSUE THREAD

**Issue by JeanValJeann** [dereuromark/cakephp-ajax#32]
Hi,

Using the Ajax Component in most my controllers and actions, I'd like to disable it for some actions where I want to use a classic jsonView via an Ajax request to get some datas. Component want me to create a view in /ajax/myAction.ctp as well ...

How can I disable the component for some actions only ?

Thanks

**Comment by dereuromark** [comment]
Set custom actions you want it to be enabled for:
https://github.com/dereuromark/cakephp-ajax/blob/master/src/Controller/Component/AjaxComponent.php#L44

Currently it only has a whitelist.
If you want a blacklist, conditionally enable the component in your code:
```
    /**
     * @return void
     */
    public function initialize()
    {
        parent::initialize();
        ...

        if (!in_array($this->request->getParam('action'), ['delete'], true)) {
            $this->loadComponent('Ajax.Ajax');
        }
    }
```
etc

**Comment by dereuromark** [comment]
I updated the docs too: https://github.com/dereuromark/cakephp-ajax/blob/master/docs/Component/Ajax.md#setup
