### ISSUE TITLE
How to load plugin Helper within AjaxView

### ISSUE THREAD

**Issue by JeanValJeann** [dereuromark/cakephp-ajax#33]
Hi,

Using Ajax Component, I'd like to use Helper within AjaxView but I can't success at it.
There is some Helper that I use commonly in my **AppView** Class that I'd like to use in **AjaxView** class. Those Helpers comes from Plugin.

How can I mention to AjaxView to load some Helper ?

**Comment by dereuromark** [comment]
We could also think about https://book.cakephp.org/3/en/views.html#event-list and events to inject helpers etc.

**Comment by dereuromark** [comment]
Or you can extend the plugin class to project level as

class AjaxView extends ....\AjaxView

and add your helpers in there.

It would automatically use that one, when you specify it as `AjaxView` (without plugin mention) then.

**Comment by dereuromark** [comment]
PR open
