### ISSUE TITLE
Incompatibility with CRUD plugin

### ISSUE THREAD

**Issue by gi-jones** [dereuromark/cakephp-ajax#41]
So I've been trying to make this work in conjunction with [https://github.com/FriendsOfCake/crud](url), but any time I have an action CRUD enabled the content is left out of the AJAX response.

I've tracked it down to this bit of code in View/AjaxView.php

```
if (isset($this->viewVars['success'])) {
   $dataToSerialize['success'] = $this->viewVars['success'];
   $view = false;
}
if ($view !== false && !isset($this->viewVars['_redirect']) && $this->_getViewFileName($view)) {
   $dataToSerialize['content'] = parent::render($view, $layout);
}
```

As you can see from [https://crud.readthedocs.io/en/latest/actions/index.html#serialize](url), CRUD will always set a success viewVar when a request works. Which then means that the Ajax plugin skips rendering.
Is there any particular reason for this behaviour? I'm not sure I understand why you would not want to render content, by definition, on a successful request?

**Comment by dereuromark** [comment]
The whole idea of the Ajax plugin is to render any action automatically as ajax only view.
So you can keep a single controller action and it works for both, including the templating behind it.

Is there a specific reason you attached the plugin for your controller and action?
What do you need it for?
Do you have a controller code example etc?

**Comment by gi-jones** [comment]
My controller looks like this:
```
class ImagesController extends AppController
{
    use \Crud\Controller\ControllerTrait;

    public function initialize()
    {
        parent::initialize();
        $this->loadComponent('Crud.Crud', [
            'actions' => [
                'Crud.Index',
                'Crud.Edit',
                'Crud.Delete',
                'pick' => [
                    'className' => 'Crud.Index'
                ]
            ]
        ]);
    }

    public function pick()
    {
        $this->Crud->on('beforePaginate', [$this->CrudSearch, '_search']);

        return $this->Crud->execute();
    }```

Basically the idea is that I use an Ajax call to show an image list with thumbnails in a pop-up. The list must be searchable, so there's a form with a search field. I could obviously set it up to work without CRUD, but the whole point was to reuse the search code defined elsewhere.
I guess it could be done without the Ajax plugin, but I just figured it makes more sense to keep the approach the same across the application.

**Comment by dereuromark** [comment]
I think you want to not cross/mix those plugins on these actions.
Better to use it when you actually need it and when it actually requires a specific AJAX response that my plugin can serve.

**Comment by gi-jones** [comment]
Ok, thanks.
