### ISSUE TITLE
Basic example for AJAX Pagination

### ISSUE THREAD

**Issue by EronarDiaras** [dereuromark/cakephp-ajax#45]
Can someone show me a simple example code for AJAX Pagination? (CakePHP 4.x)

[https://sandbox.dereuromark.de/sandbox/ajax-examples/pagination](https://sandbox.dereuromark.de/sandbox/ajax-examples/pagination)
I found an example demo here, but I can't find the code for it.

**Comment by dereuromark** [comment]
The Code is linked at the bottom, the docs should outline that you need to go into the sandbox plugin and in the Ajax controller

**Comment by EronarDiaras** [comment]
Thank you very much! I didn't notice.
