### ISSUE TITLE
[question] can this be used to submit forms?

### ISSUE THREAD

**Issue by waspinator** [dereuromark/cakephp-ajax#5]
I'm trying to submit my forms using ajax in a similar way to 

http://api.jquery.com/jquery.post or http://www.cakephp.4uk.pl/ajax/submit

I looked through some of the documentation and source, but I'm still not sure if this is the right tool.

Thanks

**Comment by dereuromark** [comment]
It will work if used properly. So yes.

**Comment by waspinator** [comment]
But I would need still to submit the form some other tool right? For example `JsHelper::serializeForm` and `JsHelper::request`. Or can cakphpe-ajax submit forms too?

**Comment by dereuromark** [comment]
It is about handling the PHP side, you need to take care of the frontend. Usually with custom jQuery or alike as shown in the sandbox ( sandbox3.dereuromark.de ).
