### ISSUE TITLE
ajax plugin not installing cakephp 5, please resolve it

### ISSUE THREAD

**Issue by shaan100** [dereuromark/cakephp-ajax#51]
![Screenshot from 2024-01-22 11-04-42](https://github.com/dereuromark/cakephp-ajax/assets/105695000/f1e59269-a1ea-4dfe-b64b-cb698bae5733)

**Comment by dereuromark** [comment]
See https://github.com/dereuromark/cakephp-ajax/releases/tag/3.0.0-RC

until released stable you will have to use `3.0.0@RC` as composer documented for RCs

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-ajax/releases/tag/3.0.0
