### ISSUE TITLE
issues after update from cakePHP 3.0 to cakePHP 3.1

### ISSUE THREAD

**Issue by githubedu** [dereuromark/cakephp-ajax#6]
Hi Mark

After running the update on composer I got the following issues:

1) during update
issue: update ok by composer but /src folder was empty.
solution: remove manually the folder and settings on composer.json, composer.lock and vendor/cakephp-plugins.php
PS: same issue happened with PHPMailer

2) before on every action I was using
         $this->viewClass = 'Ajax.Ajax'; 

but then after update I got this error message:

2015-09-27 08:53:24 Error: [Cake\View\Exception\MissingTemplateException] Template file "ajax/.ctp" is missing.
Request URL: /users/checkusername
Stack Trace:
#0 .../dereuromark/cakephp-ajax/src/View/AjaxView.php(98): Cake\View\View->_getViewFileName(NULL)
#1 .../cakephp/cakephp/src/Controller/Controller.php(598): Ajax\View\AjaxView->render(NULL, NULL)
#2 .../cakephp/cakephp/src/Routing/Dispatcher.php(120): Cake\Controller\Controller->render()
#3 .../cakephp/cakephp/src/Routing/Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#4 .../Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}

I solved changing:
$this->viewClass = 'Ajax.Ajax';  to =>   $this->viewClass = 'Ajax'; 
But, then I also need to move all *.ctp files from /Action/ajax  folder to to /Action folder.

I got it running but if there is anything that I'm doing wrong it would be nice to know to avoid me to review and test all code everytime I upgrade.

Danke, Eduardo

**Comment by dereuromark** [comment]
I already opened a ticket as this is part of a larger regression in 3.x:
https://github.com/cakephp/cakephp/issues/7452

**Comment by dereuromark** [comment]
Should be fixed now.
