### ISSUE TITLE
Why do you only show _message after a redirect?

### ISSUE THREAD

**Issue by damianoporta** [dereuromark/cakephp-ajax#7]
Hello,
any particular reason? For example in my action i do the login and set a flash message via `success()` I would like to see that message always (not only if i set a redirect).

Thanks

**Comment by dereuromark** [comment]
_message should also be in a non redirect response afaik.

**Comment by damianoporta** [comment]
@dereuromark yes it is set, but i must add it on `_serialize` to see the message on the json response. The plugin should do it automatically.

**Comment by dereuromark** [comment]
Now I understand.
You want them to be merged with the keys:
```
$serializeKeys = array('_message');
if (!empty($this->Controller->viewVars['_serialize'])) {
	$serializeKeys = array_merge($serializeKeys, $this->Controller->viewVars['_serialize']);
}
$this->Controller->viewVars['_serialize'] = $serializeKeys;

**Comment by damianoporta** [comment]
@dereuromark exactly, do you create the commit ?

**Comment by dereuromark** [comment]
If you have time and a test case in hand that would be cool.
Otherwise I can take a look this weekend maybe.

**Comment by dereuromark** [comment]
Fixed with the latest commit. Just needs a few test cases IMO.

**Comment by dereuromark** [comment]
PS: my idea would be to also allow rendering of those flash messages, maybe with an additional option key, so you can directly inject that HTML somewhere without having to use custom JS to make the HTML markup of it.

**Comment by damianoporta** [comment]
What do you think about creating a new config option to chose if "consume" the flash message or not?

**Comment by dereuromark** [comment]
what would be the use case in passing them but not consuming then?

**Comment by damianoporta** [comment]
I meant we can read the Flash and save it into _message BUT we still leave it there to let the view use it without problems. 

We create something like "removeFlashMessages" (true/false)

**Comment by dereuromark** [comment]
i know what you meant.
but that would show them twice, would it not? once in the ajax response and then on the next non ajax one. so what is the use case of that?

**Comment by damianoporta** [comment]
Yes i understand it but at the moment the view in the "content" it is not really usable. JS has to inject the messages..this sounds boring.

When the view is renderend cake should remove the Flash no?
So we should copy them into _message and the rest should work

**Comment by dereuromark** [comment]
You can just set 'flashKey' to false, then it won't put it into _message, but render it inside your layout if given, if you really want that.

**Comment by dereuromark** [comment]
Closing as the original issue should be solved now.
