### ISSUE TITLE
Flash messages are not shown in the view

### ISSUE THREAD

**Issue by damianoporta** [dereuromark/cakephp-ajax#8]
Hello,
I found a problem with Flash messages. I have seen that plugin is using `consume()` method to get messages from sessions. This is a problem when we try to print `Flash->render(...)` in the view. The `content` will never has the messages. Any workaround?

**Comment by dereuromark** [comment]
use `flashMessage`=>false to not send them to _message JSON content, but to allow to be consumed in the view.
Does that resolve this issue?
